Assignment 1 - Working with NumPy


Objective Understand the basics of NumPy, array creation, and manipulation.


Instructions 


Step 1 Install NumPy using
pip install numpy


Step 2 Create a new Python script numpy_assignment.ipynb. Import NumPy and follow these steps:  


1. Create a 1D NumPy array with integers from 1 to 20. Perform the following operations:  
  a. Calculate the sum, mean, median, and standard deviation of the elements in the array.  
  b. Find the indices of elements greater than 10 in the array.  


2. Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16.  
  a. Print the array.  
  b. Find the transpose of the array.  
  c. Calculate the row-wise and column-wise sums of the array.  


3. Create two 3 X 3 arrays filled with random integers between 1 and 20.  
  a. Perform element-wise addition, subtraction, and multiplication.  
  b. Compute the dot product of the two arrays.  


4. Reshape a 1D array of size 12 into a 3 X 4 2D array and slice the first two rows and last two columns.  


In [49]:
import numpy as np
#quetion 1
oneDArr=np.arange(1,20)
np.random.shuffle(oneDArr)
print("one D Array",oneDArr)
print("Sum of the Array : ",np.sum(oneDArr))
print("Mean of the Array : ",np.mean(oneDArr))
print("Median of the Array : ",np.median(oneDArr))
print("Standard deviation of the Array : ",np.std(oneDArr))
indice=np.where(oneDArr >10)[0]
print("element > 10",indice)

#quetion 2
twoDArr=np.arange(16).reshape(4,4)
print("two D array\n",twoDArr)
print("Transpose\n",twoDArr.T)

print("Row Wise Sum",np.sum(twoDArr,axis=1))
print("Cloumn Wise Sum",np.sum(twoDArr,axis=0))

#ques 3
array1=np.random.randint(1,20,(3,3))
array2=np.random.randint(1,20,(3,3))
print("array1\n",array1)
print("array2\n",array2)
print("Additon\n",array1+array2)
print("Subtraction\n",array1-array2)
print("Multiplication\n",array1*array2)
print("Dot Product\n",np.dot(array1,array2))

#quest 4
arr=np.arange(12)
arr_reshape=arr.reshape(3,4)
print("reshape 1D to 2D\n",arr_reshape)
arr_reshape[0:2, 2:]


one D Array [ 6  1 13  2 12 16 14  5 17  8 11  7 10 18 15 19  9  3  4]
Sum of the Array :  190
Mean of the Array :  10.0
Median of the Array :  10.0
Standard deviation of the Array :  5.477225575051661
element > 10 [ 2  4  5  6  8 10 13 14 15]
two D array
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Transpose
 [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
Row Wise Sum [ 6 22 38 54]
Cloumn Wise Sum [24 28 32 36]
array1
 [[ 6  2 18]
 [ 3  8  4]
 [10 17  7]]
array2
 [[ 6 19 16]
 [ 6 16 13]
 [ 8  4 16]]
Additon
 [[12 21 34]
 [ 9 24 17]
 [18 21 23]]
Subtraction
 [[  0 -17   2]
 [ -3  -8  -9]
 [  2  13  -9]]
Multiplication
 [[ 36  38 288]
 [ 18 128  52]
 [ 80  68 112]]
Dot Product
 [[192 218 410]
 [ 98 201 216]
 [218 490 493]]
reshape 1D to 2D
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[2, 3],
       [6, 7]])